/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dashboard/analysis/': RouteRecordInfo<'/dashboard/analysis/', '/dashboard/analysis', Record<never, never>, Record<never, never>>,
    '/dashboard/monitor/': RouteRecordInfo<'/dashboard/monitor/', '/dashboard/monitor', Record<never, never>, Record<never, never>>,
    '/dashboard/workbench/': RouteRecordInfo<'/dashboard/workbench/', '/dashboard/workbench', Record<never, never>, Record<never, never>>,
  }
}
